// Builds database/seed/002_seed_inventory.sql from database/seed/inventory-source.txt
// and prints a verification report (row counts per screenshot section, zero-stock items, duplicates).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = join(root, "database", "seed", "inventory-source.txt");
const outPath = join(root, "database", "seed", "002_seed_inventory.sql");

// Rows visible in each screenshot section (counted from the images).
const EXPECTED_ROWS = { "S1-A": 42, "S1-B": 42, "S1-C": 20, "S1-D": 21, "S2-A": 42, "S2-B": 33, "S2-C": 37 };

const CATEGORY_RULES = [
  ["GLP-1", /^(mounjaro|zepbound|ozempic|wegovy|trulicity|victoza|liraglutide|rybelsus)\b/i],
  ["Diabetes", /^(basaglar|humulin|humalog|insulin lispro|lantus|novolin|novalog|toujeo|tresiba|farxiga|dapagliflozin|invokana|januvia|janumet|jardiance|synjardy|trijardy|tradjenta|xigduo)\b/i],
  ["Inhalers", /^(airsupra|anoro|arnuity|breo|breztri|combivent|dulera|incruse|qvar|spiriva|stiolto|symbicort|trelegy|ventolin|advair|albuterol|wixela)\b/i],
  ["Cardiovascular", /^(eliquis|xarelto|brilinta|entresto|praluent|rapatha)\b/i],
  ["Gastrointestinal", /^(linzess|movantik|trulance)\b/i],
  ["Dermatology", /^(nemluvio)\b/i],
];

const categoryFor = (name) => CATEGORY_RULES.find(([, re]) => re.test(name))?.[0] ?? "Other";
const ndcFor = (name) => name.match(/NDC\s*([0-9]+(?:-[0-9]+)+)/i)?.[1] ?? null;
const sql = (v) => (v === null ? "null" : `'${String(v).replace(/'/g, "''")}'`);

const rows = [];
const counts = {};
let section = null;
for (const raw of readFileSync(sourcePath, "utf8").split(/\r?\n/)) {
  const line = raw.trim();
  if (!line || line.startsWith("# ")) continue;
  if (line.startsWith("##")) {
    section = line.slice(2).trim().split(" ")[0];
    counts[section] = 0;
    continue;
  }
  const [namePart, qtyPart] = line.split("|");
  const name = namePart.replace(/\s+/g, " ").trim();
  const qty = Number(qtyPart.trim());
  if (!name || !Number.isInteger(qty) || qty < 0) throw new Error(`Bad line: ${line}`);
  rows.push({ section, name, qty, category: categoryFor(name), sku: ndcFor(name) });
  counts[section]++;
}

// ---- verification report ----
let ok = true;
console.log("Rows per screenshot section (found / expected):");
for (const [s, expected] of Object.entries(EXPECTED_ROWS)) {
  const good = counts[s] === expected;
  ok &&= good;
  console.log(`  ${s}: ${counts[s]} / ${expected} ${good ? "OK" : "MISMATCH"}`);
}
const seen = new Map();
for (const r of rows) {
  const key = `${r.name}`;
  seen.set(key, [...(seen.get(key) ?? []), r]);
}
const dups = [...seen.values()].filter((v) => v.length > 1);
console.log(`\nTotal products: ${rows.length}`);
console.log(`Total units:    ${rows.reduce((a, r) => a + r.qty, 0)}`);
console.log(`Zero-stock:     ${rows.filter((r) => r.qty === 0).length}`);
console.log(`Exact same name listed more than once in the screenshots (kept as separate rows): ${dups.length}`);
for (const d of dups) console.log(`  "${d[0].name}" -> quantities ${d.map((x) => x.qty).join(", ")}`);
const byCat = {};
for (const r of rows) byCat[r.category] = (byCat[r.category] ?? 0) + 1;
console.log("By category:", byCat);
if (!ok) {
  console.error("\nRow counts do not match the screenshots - fix inventory-source.txt");
  process.exit(1);
}

const values = rows
  .map((r) => `    (${sql(r.name)}, ${sql(r.sku)}, ${sql(r.category)}, ${r.qty})`)
  .join(",\n");

writeFileSync(
  outPath,
  `-- Generated by scripts/generate-seed.mjs from database/seed/inventory-source.txt
-- ${rows.length} products. Safe to run more than once: it does nothing if products already exist.

do $seed$
begin
  if exists (select 1 from public.products) then
    raise notice 'Products already exist - seed skipped.';
    return;
  end if;

  with src (product_name, sku, category, inventory) as (
    values
${values}
  ),
  inserted as (
    insert into public.products (product_name, sku, category, inventory)
    select product_name, sku, category, inventory from src
    returning id, inventory
  )
  insert into public.inventory_transactions
    (product_id, previous_quantity, quantity_change, new_quantity, transaction_type, note, created_by_name)
  select id, 0, inventory, inventory, 'initial_stock', 'Initial inventory import', 'System'
  from inserted
  where inventory > 0;
end
$seed$;
`,
);
console.log(`\nWrote ${outPath}`);
